<!DOCTYPE html>
<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>Curso PDO - Scholl of Net - Área Administrativa</title>

        <!-- Bootstrap core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="css/navbar.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="assets/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <style>
            h1, h2, h3, h4{
                color: #990000;
            }
        </style>
    </head>

    <body>
        <div class="container">

            <!-- Static navbar -->
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" 
                                data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand azul" href="/admin">Área Administrativa</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/admin">Home Admin</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                                   role="button" aria-haspopup="true" 
                                   aria-expanded="false">Usuário <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/inserirUsuario">Cadastrar</a></li>
                                    <li><a href="/usuario">Listar</a></li>
                                    <li><a href="/senhaUsuario?id=<?php echo $_SESSION['username']->id;?>">Mudar minha Senha</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                                   role="button" aria-haspopup="true" 
                                   aria-expanded="false">Aluno <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/inserir">Cadastrar</a></li>
                                    <li><a href="/admin">Listar</a></li>                                    
                                </ul>
                            </li>
  
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <form class="navbar-form navbar-left" method="post" action="/busca" role="search">
                                    <div class="form-group">
                                        <input type="text" name="busca" class="form-control" placeholder="Buscar Aluno">
                                    </div>
                                    <button type="submit" class="btn btn-default">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </form>   
                            </li>
                            <p class="navbar-text pull-right">
                                <?php echo $_SESSION['username']->nome; ?> | <a href="/logout"> 
                                    <span class="glyphicon glyphicon-user"></span>&nbsp; Sair</a></p>


                        </ul>


                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>
            <hr>

            <div class="page-header">
                <h1>Área Administrativa</h1>
            </div>
            <?php
            if (isset($_SESSION['erros']) && count($_SESSION['erros']) > 0) {
                ?>
                <div class="alert alert-danger">
                    <ul>
                        <?php foreach ($_SESSION['erros'] as $erro) :
                            ?>
                            <li><?php echo $erro; ?></li>
                            <?php
                        endforeach;
                        unset($_SESSION['erros']);
                        ?>
                    </ul>
                </div>

                <?php
            }

            if (isset($_SESSION['status'])) {
                ?>
                <div class="alert alert-success" role="alert">
                    <p>
                        <?php
                        echo $_SESSION['status'];
                        unset($_SESSION['status']);
                        ?>

                    </p>
                </div>
                <?php
            }
            ?>

            <div>
<?php $this->content(); ?>
            </div>


        </div> <!-- /container -->


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="jquery.min.js"><\/script>')</script>
        <script src="js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>
